### PR TITLE
Adding 2015 actions plus two more recent

### PR DESCRIPTION
**Pull request by nataliyaned**

### CODE REVIEW

**Comment by organizejs** [comment]
are you adding via excel?

**Comment by nataliyaned** [comment]
I am. Is there a better way?

**Comment by organizejs** [comment]
its fine, especially if you're adding a few things at once. but it makes the code-review harder because of all the file changes.

if its just a few events you're adding, it might be better to add via a new file (like the way we were doing before)

**Comment by nataliyaned** [comment]
Got it. I'll keep it only for the especially large batches.

**Comment by organizejs** [comment]
actually i should be able to make some updates to make excel updates easier / more readable if that's youre prefered way of adding events. might be worth it

**Comment by nataliyaned** [comment]
It is a lot more convenient. Whatever is the best tradeoff in terms of time.

**Comment by organizejs** [comment]
i'll work on it, might have to be the weekend after though.

**Comment by nataliyaned** [comment]
Okay. Sounds good. I'll hold off on more batch PRs until then.

**Comment by organizejs** [comment]
this pr addresses: #161 #162 #163

**Pull request merged**
